version: '3.7'

services:

  app:
    build:
      context: .
    restart: always
    ports:
      - "8000:8000"
    {% if cookiecutter.use_postgres == 'y' or cookiecutter.use_redis == 'y' %}
    depends_on:
      {% if cookiecutter.use_postgres == 'y' %}- postgres{% endif %}
      {% if cookiecutter.use_redis == 'y' %}- redis{% endif %}
    environment:
      {% if cookiecutter.use_redis == 'y' -%}- REDIS_URL=redis://redis{%- endif %}
      {% if cookiecutter.use_postgres -%}
      - PGHOST=postgres
      - PGDATABASE=postgres
      {%- endif %}
  {%- endif %}

  {% if cookiecutter.use_postgres == 'y' -%}
  postgres:
    image: postgres:11-alpine
    hostname: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8001:80"
    depends_on:
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres
      - PGADMIN_DEFAULT_PASSWORD=postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./contrib/pgadmin-server.json:/pgadmin4/servers.json
  {%- endif %}

  {% if cookiecutter.use_redis == 'y' -%}
  redis:
    image: redis:alpine
    hostname: redis
    restart: always
  {%- endif %}

{% if cookiecutter.use_postgres == 'y' or cookiecutter.use_redis == 'y' -%}
volumes:
  {% if cookiecutter.use_redis == 'y' -%}postgres-data:{%- endif %}
  {% if cookiecutter.use_postgres == 'y' -%}pgadmin-data:{%- endif %}
{%- endif %}
