version: '3.7'

services:

  api:
    build:
      context: .
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    environment:
      - REDIS_URL=redis://redis

  postgres:
    image: postgres:11-alpine
    hostname: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    hostname: redis
    restart: always

volumes:
  postgres-data:
