version: '3.7'

services:

  app:
    build:
      context: ""
    restart: always
    ports:
      - "8000:8000"
    <%_ if (use_postgres || use_redis) { _%>
    depends_on:
      <%_ if (use_postgres) { _%>- postgres<%_ } _%>
      <%_ if (use_redis) { _%>- redis<%_ } _%>
    environment:
      <%_ if (use_redis) { _%>- REDIS_URL=redis://redis<%_ } _%>
      <%_ if (use_postgres) { _%>
      - PGHOST=postgres
      - PGDATABASE=postgres
      <%_ } _%>
  <%_ } _%>

  <%_ if (use_postgres) { _%>
  postgres:
    image: postgres:alpine
    hostname: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres
      - PGADMIN_DEFAULT_PASSWORD=postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./pgadmin-server.json:/pgadmin4/servers.json
  <%_ } _%>

  <%_ if (use_redis) { _%>
  redis:
    image: redis:alpine
    hostname: redis
    restart: always
  <%_ } _%>

<%_ if (use_postgres || use_redis) { _%>
volumes:
  <%_ if (use_redis) { _%>postgres-data:<%_ } _%>
  <%_ if (use_postgres) { _%>pgadmin-data:<%_ } _%>
<%_ } _%>
