name: tests

on: [push]

jobs:
    tests:

        runs-on: ubuntu-latest
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                python-version: [3.6, 3.7, 3.8]
                node-version: [8.x, 10.x, 12.x]
                exclude:
                    -   os: macos-latest
                        python-version: 3.8
                    -   os: windows-latest
                        python-version: 3.6
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v2
            -   name: Set up Python
                uses: actions/setup-python@v2
                with:
                    python-version: ${{ matrix.python-version }}
            -   name: Display Python version
                run: python -c "import sys; print(sys.version)"
